<a href="https://colab.research.google.com/github/LargeMan/CAP4630/blob/master/HW_1/HW_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Homework 1

When multiplying two matrices, the number of ***columns*** in the first matrix must equal the number of ***rows*** in the second.

For example, the following matrix multiplication is valid:

\begin{equation*}
  \begin{bmatrix}
  1 & 2 & 3\\
  4 & 5 & 6
  \end{bmatrix}
  *
  \begin{bmatrix}
  1 & 2\\
  3 & 4\\
  5 & 6
  \end{bmatrix}
  = \begin{bmatrix}
  22 & 28\\
  49 & 64
  \end{bmatrix}
\end{equation*}
The final matrix is the result of multiplying every **row** of the first matrix by every **column** of the second (hence why number of rows in the first has to equal number of columns in the second).<br/><br/>


Below is the answer to the above example, but before any multiplication or addition is done.<br/><br/>

\begin{equation*}
  = \begin{bmatrix}
  [(1*1)+(2*3)+(3*5)] & [(1*2)+(2*4)+(3*6)]\\
  [(4*1)+(5*3)+(6*5)] & [(4*2)+(5*4)+(6*6)]
  \end{bmatrix} 
\end{equation*}
<br/>

On the other hand, matrices that do not have matching numbers of rows/columns cannot be multiplied. The following example is invalid:<br/>


\begin{equation*}
  \begin{bmatrix}
  1 & 2 & 3\\
  4 & 5 & 6
  \end{bmatrix}
  *
  \begin{bmatrix}
  1 & 2\\
  3 & 4
  \end{bmatrix}
\end{equation*}
<br/>

The following code defines a function that will take a list of matrices as an input, and return the result of every matrix multipled by each other in order. If this fails, then an error is printed describing the error.

In [0]:
import numpy as np
from typing import List

The following function takes a list of matricies and multiplies each
of them in the order they appear in the list. That is, the first matrix in the list is multiplied by the second, the result is multiplied by the third, and so
on.

In [0]:
def multiply_matrices(inval : List[np.ndarray]):
  '''Multiplies a list of matrices and returns the result (or None)'''
  if not inval: # empty list is consided 'False' by python
    print("ERROR: The list is empty!")
    return

  matrices = inval.copy()
  prev = matrices.pop(0)

  try:
    for i, mat in enumerate(matrices):
      # check if element is not a np array
      if not isinstance(mat, np.ndarray):
        print("Element '{}' at index {} of the input list " +
              "is not a np array!".format(mat, i+1))
        return None

      prev = np.matmul(prev, mat)
      #print(prev)
  except ValueError as e:
    # Prints an error describing the problem matrices
    print("Matrix\n\n{}\n\nhas {} columns, but matrix\n\n{}\n\nhas {} rows!\n".format(
        prev, np.size(prev, 1), mat, np.size(mat, 0)))
    print("These numbers must be equal to be a valid operation!\n")
    print("This error occurs at index {} of the input list;".format(i+1))
    print("the matrix prior to this is\n{}\n".format(inval[i]))
    return None

   
  return prev

## Test Case for Type Exception

In [68]:
# NOTE: The homework said the input list should consist of np.arrays,
#       so the following will fail. If scalar support should be a thing,
#       please let me know!

a = np.array([[1, 0], [0, 1]])
b = np.array([[4, 1], [2, 2]])

x = multiply_matrices([b,3])
print(x)

Element '{}' at index {} of the input list is not a np array!
None


## Test Cases for valid input list of numpy arrays
This test case is equivalent to the following equation:
$$
\begin{equation*}
  \begin{bmatrix}
  1 & 4\\
  8 & 1
  \end{bmatrix}
  *
  \begin{bmatrix}
  4 & 1\\
  2 & 2
  \end{bmatrix}
  = \begin{bmatrix}
  12 & 9\\
  34 & 10
  \end{bmatrix}
\end{equation*}
$$

In [69]:
a = np.array([[1, 4], [8, 1]])
b = np.array([[4, 1], [2, 2]])

x = multiply_matrices([a, b])
print(x)

[[12  9]
 [34 10]]


This test case is equivalent to the following equation:
$$
\begin{equation*}
  \begin{bmatrix}
  1 & 2 & 3\\
  4 & 5 & 6
  \end{bmatrix}
  *
  \begin{bmatrix}
  1 & 2\\
  3 & 4\\
  5 & 6
  \end{bmatrix}
  = \begin{bmatrix}
  22 & 28\\
  49 & 64
  \end{bmatrix}
\end{equation*}
$$

In [70]:
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[1, 2], [3, 4], [5, 6]])

y = multiply_matrices([c, d])
print(x)

[[12  9]
 [34 10]]


This test case is equivalent to the following equation:
This test case is equivalent to the following equation:
$$
\begin{equation*}
  \left(
  \left(
  \left(
  \begin{bmatrix}
  1 & 2 & 3\\
  4 & 5 & 6
  \end{bmatrix}
  *
  \begin{bmatrix}
  1 & 2\\
  3 & 4\\
  5 & 6
  \end{bmatrix}
  \right)
  *
  \begin{bmatrix}
  1 & 4\\
  8 & 1
  \end{bmatrix}
  \right)
  *
  \begin{bmatrix}
  4 & 1\\
  2 & 2
  \end{bmatrix}
  \right)
  = \begin{bmatrix}
  1856 & 2408\\
  4214 & 5468
  \end{bmatrix}
\end{equation*}
$$

## Test Case for empty list

 


In [71]:
multiply_matrices([])

ERROR: The list is empty!


## Test Case for single list

In [72]:
multiply_matrices([np.eye(3)])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Test Case for incompatible matrices

In [73]:
multiply_matrices([np.eye(3),np.eye(3),np.ones(2)])

Matrix

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

has 3 columns, but matrix

[1. 1.]

has 2 rows!

These numbers must be equal to be a valid operation!

This error occurs at index 2 of the input list;
the matrix prior to this is
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

